<script lang="ts">
import { programmeName } from "#lib/assets/config.js"
import Head from "#lib/components/Head.svelte"
import { page } from "$app/state"
import { getEditableSubmission, updateSubmissionForm } from "./edit.remote"

const sub = $derived(await getEditableSubmission(page.params.id ?? ""))

const imageSrc = $derived(
	sub.image?.hash ? `/submissions/images/${sub.image.hash}` : null
)
</script>

<Head title="Update your submission" noindex />

<a href="/submissions" class="text-sm hover:underline">
	Back to your submissions
</a>

<h1 class="pt-4 text-2xl">Update your submission</h1>

{#if sub.reviewNotes}
	<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4">
		<p class="font-semibold text-amber-800">Changes requested</p>
		<p class="pt-1 text-sm whitespace-pre-wrap text-amber-900">
			{sub.reviewNotes}
		</p>
	</div>
{/if}

<form {...updateSubmissionForm} enctype="multipart/form-data" class="pt-8">
	<input {...updateSubmissionForm.fields.id.as("hidden", sub.id)}>

	<label>
		<span>Submission image or screenshot</span>
		{#if imageSrc}
			<img
				src={imageSrc}
				alt="Your current submission"
				class="my-2 w-full max-w-md rounded-lg object-cover"
			>
		{/if}
		<input {...updateSubmissionForm.fields.image.as("file")}>
		{#each updateSubmissionForm.fields.image.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
		<p class="pt-2 text-sm text-neutral-600">
			Leave this blank to keep your current image. A screenshot of your
			bots in action is great &ndash; the
			<a target="_blank" href="/your-bots">Your bots</a>
			page or the page for that specific bot works well. You can link your
			code in the <b>Code URL</b> field below.
		</p>
	</label>

	<label>
		<span>Submission name</span>
		<input
			{...updateSubmissionForm.fields.name.as("text", sub.name)}
			required
		>
		{#each updateSubmissionForm.fields.name.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
		<p class="pt-2 text-sm text-neutral-600">
			The name of the bots (or team of bots) which you are submitting.
		</p>
	</label>

	<label>
		<span>Submission description</span>
		<textarea
			{...updateSubmissionForm.fields.description.as(
				"text",
				sub.description
			)}
			required
		></textarea>
		{#each updateSubmissionForm.fields.description.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
	</label>

	<label>
		<span>Code URL</span>
		<input
			{...updateSubmissionForm.fields.codeUrl.as("url", sub.codeUrl)}
			placeholder="https://github.com/..."
			required
		>
		{#each updateSubmissionForm.fields.codeUrl.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
		<p class="pt-2 text-sm text-neutral-600">
			A link to your project's code repository on GitHub or similar.
		</p>
	</label>

	<label>
		<span>
			<input
				{...updateSubmissionForm.fields.ai.as("checkbox")}
				checked={sub.ai}
			>
			<span class="pl-2"
				>I used generative AI in building this project</span
			>
		</span>
		{#each updateSubmissionForm.fields.ai.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
		<p class="text-sm text-neutral-600">
			Generally, up to 1/3 of the time spent on a project can be completed
			with generative AI assistance. Projects with more than 1/3 of their
			time attributed to AI code generation, or for which a significant
			portion of their final code is generated by AI, may have their
			rewarded hours manually adjusted.
		</p>
	</label>

	<label>
		<span>How did you hear about this programme?</span>
		<textarea
			{...updateSubmissionForm.fields.howHear.as(
				"text",
				sub.howHear ?? ""
			)}
		></textarea>
		{#each updateSubmissionForm.fields.howHear.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
	</label>

	<label>
		<span>What do you think {programmeName} did well?</span>
		<textarea
			{...updateSubmissionForm.fields.howDoingWell.as(
				"text",
				sub.howDoingWell ?? ""
			)}
		></textarea>
		{#each updateSubmissionForm.fields.howDoingWell.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
	</label>

	<label>
		<span
			>How could {programmeName} improve if it were to run again in
			future?</span
		>
		<textarea
			{...updateSubmissionForm.fields.howImprove.as(
				"text",
				sub.howImprove ?? ""
			)}
		></textarea>
		{#each updateSubmissionForm.fields.howImprove.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
	</label>

	<label>
		<span
			>On a scale of 0 (least likely) to 10 (most likely), how likely
			would you be to recommend this programme (or a very similar future
			one) to a friend?</span
		>
		<input
			{...updateSubmissionForm.fields.howLikelyRecommend.as(
				"number",
				sub.howLikelyRecommend
			)}
			required
			min="0"
			max="10"
			step="1"
		>
		{#each updateSubmissionForm.fields.howLikelyRecommend.issues() ?? [] as issue}
			<span class="pt-2 text-sm text-red-500">{issue.message}</span>
		{/each}
	</label>

	{#if updateSubmissionForm.fields.allIssues()?.length}
		<div class="pb-6" role="alert">
			<p class="font-bold text-red-500">
				Please fix the following issues:
			</p>
			<ul class="list-disc pl-6 text-sm text-red-500">
				{#each updateSubmissionForm.fields.allIssues() ?? [] as issue}
					<li>{issue.message}</li>
				{/each}
			</ul>
		</div>
	{/if}

	<button
		disabled={updateSubmissionForm.pending > 0}
		type="submit"
		class="btn btn-primary {updateSubmissionForm.pending > 0
			? 'bg-neutral-200 text-neutral-500 hover:bg-neutral-200 active:bg-neutral-200 opacity-60'
			: ''}"
	>
		{updateSubmissionForm.pending > 0
			? "Saving..."
			: "Save and resubmit"}
	</button>
</form>
